####################################################################
## Approve the PR based on author                                 ##
####################################################################

name: Auto-approve

on:
  pull_request:
    types:
      - opened

jobs:
  pr-automation:
    runs-on: ubuntu-latest
    steps:
    - name: Auto approve PRs based on author
      uses: hmarr/auto-approve-action@v4.0.0
      if: github.actor == 'scalesec-automation-bot'
      with:
        github-token: ${{ secrets.GH_TOKEN }}
