####################################################################
## Add an 'automerge' label to the PR based on file touched       ##
####################################################################

name: Labeler

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "policies/org_policy.json"

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
