###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'main'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      # Upgraded linter v3 -> v4
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v4
        env:
          DEFAULT_BRANCH: 'main'
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_TERRAFORM: true
          VALIDATE_PYTHON_PYLINT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
