name: Terraform lint and apply

### 
# terrafrom action repo/docs
#
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: TF stuff
    steps:
    - uses: hashicorp/setup-terraform@v1


